/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author admin
 */
public class Otras_bebidas_3 extends javax.swing.JFrame {

    /**
     * Creates new form Otras_bebidas_3
     */
    public Otras_bebidas_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jt_f_naranja = new javax.swing.JButton();
        jb_agua = new javax.swing.JButton();
        jb_sprite = new javax.swing.JButton();
        jb_cocacola = new javax.swing.JButton();
        jb_acuarius = new javax.swing.JButton();
        jb_tinto = new javax.swing.JButton();
        jb_agua_gas = new javax.swing.JButton();
        jb_corto = new javax.swing.JButton();
        jb_nestea = new javax.swing.JButton();
        jt_f_limon = new javax.swing.JButton();
        jb_canion = new javax.swing.JButton();
        jb_martini = new javax.swing.JButton();
        jb_blanco = new javax.swing.JButton();
        jb_cania = new javax.swing.JButton();
        jb_rosado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_info_add_ticket_otras_bebidas = new javax.swing.JTextArea();
        jb_aniadir_ticket_iotras_bebidas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));

        jt_f_naranja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jt_f_naranja.setText("Fanta Naranja");
        jt_f_naranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_f_naranjaActionPerformed(evt);
            }
        });

        jb_agua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_agua.setText("Agua");
        jb_agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_aguaActionPerformed(evt);
            }
        });

        jb_sprite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_sprite.setText("Sprite");
        jb_sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_spriteActionPerformed(evt);
            }
        });

        jb_cocacola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_cocacola.setText("Coca Cola");
        jb_cocacola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cocacolaActionPerformed(evt);
            }
        });

        jb_acuarius.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_acuarius.setText("Acuarius");
        jb_acuarius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_acuariusActionPerformed(evt);
            }
        });

        jb_tinto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_tinto.setText("Tinto");
        jb_tinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_tintoActionPerformed(evt);
            }
        });

        jb_agua_gas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_agua_gas.setText("Agua con Gas");
        jb_agua_gas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agua_gasActionPerformed(evt);
            }
        });

        jb_corto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_corto.setText("Corto");
        jb_corto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cortoActionPerformed(evt);
            }
        });

        jb_nestea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_nestea.setText("Nestea");
        jb_nestea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nesteaActionPerformed(evt);
            }
        });

        jt_f_limon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jt_f_limon.setText("Fanta Limon");
        jt_f_limon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_f_limonActionPerformed(evt);
            }
        });

        jb_canion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_canion.setText("Cañón");
        jb_canion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_canionActionPerformed(evt);
            }
        });

        jb_martini.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_martini.setText("Martini");
        jb_martini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_martiniActionPerformed(evt);
            }
        });

        jb_blanco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_blanco.setText("Blanco");
        jb_blanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_blancoActionPerformed(evt);
            }
        });

        jb_cania.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_cania.setText("Caña");
        jb_cania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_caniaActionPerformed(evt);
            }
        });

        jb_rosado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_rosado.setText("Rosado");
        jb_rosado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_rosadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jb_acuarius, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_nestea, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jb_cocacola, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_f_naranja, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_f_limon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jb_agua, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_agua_gas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_martini, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jb_corto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jb_cania, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jb_blanco, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jb_rosado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_tinto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_canion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_cocacola, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jt_f_naranja, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jt_f_limon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_acuarius, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_nestea, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_agua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_agua_gas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_martini, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_corto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_cania, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_canion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_blanco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_tinto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_rosado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jta_info_add_ticket_otras_bebidas.setEditable(false);
        jta_info_add_ticket_otras_bebidas.setColumns(20);
        jta_info_add_ticket_otras_bebidas.setRows(5);
        jScrollPane1.setViewportView(jta_info_add_ticket_otras_bebidas);

        jb_aniadir_ticket_iotras_bebidas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb_aniadir_ticket_iotras_bebidas.setText("AÑADIR AL TICKET");
        jb_aniadir_ticket_iotras_bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_aniadir_ticket_iotras_bebidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_aniadir_ticket_iotras_bebidas))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_aniadir_ticket_iotras_bebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_f_naranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_f_naranjaActionPerformed
        // añade fanta naranja al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jt_f_naranjaActionPerformed

    private void jb_aguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_aguaActionPerformed
        // añade agua mineral al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jb_aguaActionPerformed

    private void jb_spriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_spriteActionPerformed
        // añade sprite al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jb_spriteActionPerformed

    private void jb_cocacolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cocacolaActionPerformed
        // añade Coca cola al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jb_cocacolaActionPerformed

    private void jb_acuariusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_acuariusActionPerformed
        // añade acuarius al jta_info_add_ticket_otras_bebidas:
    }//GEN-LAST:event_jb_acuariusActionPerformed

    private void jb_tintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_tintoActionPerformed
        // añade vino tinto al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jb_tintoActionPerformed

    private void jb_agua_gasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agua_gasActionPerformed
        // añade agua con gas  al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jb_agua_gasActionPerformed

    private void jb_cortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cortoActionPerformed
        // añade corto al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jb_cortoActionPerformed

    private void jb_nesteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nesteaActionPerformed
        // añade nestea al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jb_nesteaActionPerformed

    private void jt_f_limonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_f_limonActionPerformed
        // añade fanta limón al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jt_f_limonActionPerformed

    private void jb_canionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_canionActionPerformed
        // añade cañón al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jb_canionActionPerformed

    private void jb_martiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_martiniActionPerformed
        /// añade martini al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jb_martiniActionPerformed

    private void jb_blancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_blancoActionPerformed
        // añade vino blanco al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jb_blancoActionPerformed

    private void jb_caniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_caniaActionPerformed
        // añade caña al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jb_caniaActionPerformed

    private void jb_rosadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_rosadoActionPerformed
        // añade vino rosado al jta_info_add_ticket_otras_bebidas
    }//GEN-LAST:event_jb_rosadoActionPerformed

    private void jb_aniadir_ticket_iotras_bebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_aniadir_ticket_iotras_bebidasActionPerformed
        //añadir al ticket seleccionado los productos que se han recogido
        //OJO-- esto debe cerrar la ventana y volver al main
         Main_botones_3.otrasbebe3.dispose();
    }//GEN-LAST:event_jb_aniadir_ticket_iotras_bebidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Otras_bebidas_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Otras_bebidas_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Otras_bebidas_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Otras_bebidas_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Otras_bebidas_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_acuarius;
    private javax.swing.JButton jb_agua;
    private javax.swing.JButton jb_agua_gas;
    private javax.swing.JButton jb_aniadir_ticket_iotras_bebidas;
    private javax.swing.JButton jb_blanco;
    private javax.swing.JButton jb_cania;
    private javax.swing.JButton jb_canion;
    private javax.swing.JButton jb_cocacola;
    private javax.swing.JButton jb_corto;
    private javax.swing.JButton jb_martini;
    private javax.swing.JButton jb_nestea;
    private javax.swing.JButton jb_rosado;
    private javax.swing.JButton jb_sprite;
    private javax.swing.JButton jb_tinto;
    private javax.swing.JButton jt_f_limon;
    private javax.swing.JButton jt_f_naranja;
    private javax.swing.JTextArea jta_info_add_ticket_otras_bebidas;
    // End of variables declaration//GEN-END:variables
}
